# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://nils2000.github.io/try_out_nbdev/"

git_url = "https://github.com/nils2000/try_out_nbdev/tree/master/"

def custom_doc_links(name): return None
